-- ============================================================
-- Esquema H2 convertido a partir do SQL Server (esquema-ddl.sql)
-- ============================================================

-- Tabelas principais (sem FK)

CREATE TABLE IF NOT EXISTS T696ACAO (
    SQ_ACO INT AUTO_INCREMENT PRIMARY KEY,
    SQ_PLJ_EMP INT NOT NULL,
    CD_UND INT NOT NULL,
    DE_ACO VARCHAR(1000) NOT NULL,
    DE_RST_ESP VARCHAR(1000) NOT NULL,
    DT_CCL TIMESTAMP NOT NULL,
    MT_USU_RSP VARCHAR(10) NOT NULL,
    PC_REA DECIMAL(5,2) NULL,
    DE_HST CLOB NULL,
    MT_USU_CRI VARCHAR(10) NOT NULL,
    NM_USU_CRI VARCHAR(100) NOT NULL,
    DH_CRI TIMESTAMP NOT NULL,
    MT_USU_ALT VARCHAR(10) NULL,
    NM_USU_ALT VARCHAR(100) NULL,
    DH_ALT TIMESTAMP NULL,
    ST_ACO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS T696FORU (
    SQ_FRU INT AUTO_INCREMENT PRIMARY KEY,
    SQ_TP_FRU INT NOT NULL,
    CD_UND INT NOT NULL,
    SQ_PAT_MIN INT NOT NULL,
    NM_FRU VARCHAR(100) NOT NULL,
    DH_INI TIMESTAMP NOT NULL,
    DH_TRM TIMESTAMP NOT NULL,
    DE_LOC VARCHAR(100) NOT NULL,
    DE_OUT_AS VARCHAR(1000) NULL,
    DE_TRT_OUT_AS CLOB NULL,
    DE_HST CLOB NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_FRU INT NOT NULL
);

CREATE TABLE IF NOT EXISTS T696GPRM (
    SQ_GP_REG_MTA INT AUTO_INCREMENT PRIMARY KEY,
    NM_GP_REG_MTA VARCHAR(100) NOT NULL,
    NM_CUR_GP_REG VARCHAR(15) NOT NULL,
    TP_PER_GP_REG INT NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ATZ TIMESTAMP NOT NULL,
    ST_GP_REG_MTA INT NOT NULL
);

CREATE TABLE IF NOT EXISTS T696GPUN (
    SQ_GP_UND INT AUTO_INCREMENT PRIMARY KEY,
    NM_GP_UND VARCHAR(100) NOT NULL,
    MT_USU_ALT VARCHAR(10) NULL,
    NM_USU_ALT VARCHAR(100) NULL,
    DH_ALT TIMESTAMP NULL,
    ST_GP_UND INT NOT NULL
);

CREATE TABLE IF NOT EXISTS T696GRVR (
    SQ_GP_VR_REA INT AUTO_INCREMENT PRIMARY KEY,
    NM_GP_VR_REA VARCHAR(100) NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_GP_VR_REA INT NOT NULL,
    TP_PER_VR_REA INT NULL
);

CREATE TABLE IF NOT EXISTS T696HPRO (
    SQ_HST_PRC INT AUTO_INCREMENT PRIMARY KEY,
    NM_PRC VARCHAR(100) NOT NULL,
    DE_PRM VARCHAR(255) NOT NULL,
    DE_RST VARCHAR(100) NOT NULL,
    OB_PRC CLOB NOT NULL,
    DH_INI_PRC TIMESTAMP NOT NULL,
    DH_FIM_PRC TIMESTAMP NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS T696LTVR (
    SQ_LOT BIGINT AUTO_INCREMENT PRIMARY KEY,
    CD_LOT INT NULL,
    DT_REF TIMESTAMP NULL,
    DT_LOT TIMESTAMP NOT NULL,
    CD_SIS VARCHAR(20) NOT NULL,
    QT_REG INT NULL,
    VR_TOT_DIA DECIMAL(15,2) NULL,
    VR_TOT_MEN DECIMAL(15,2) NULL,
    VR_TOT_ANU DECIMAL(15,2) NULL,
    ST_LOT INT NOT NULL
);

CREATE TABLE IF NOT EXISTS T696MOAD (
    SQ_MOD_AVL_DSP INT AUTO_INCREMENT PRIMARY KEY,
    NM_MOD_AVL_DSP VARCHAR(100) NOT NULL,
    ID_FIN INT NOT NULL,
    DT_INI_VIG TIMESTAMP NOT NULL,
    DT_FIM_VIG TIMESTAMP NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS T696NATV (
    SQ_NAT INT AUTO_INCREMENT PRIMARY KEY,
    NM_NAT VARCHAR(100) NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    FT_DIV INT NULL,
    NM_NAT_RLT VARCHAR(100) NULL
);

CREATE TABLE IF NOT EXISTS T696ORAC (
    SQ_ORI_ACO INT AUTO_INCREMENT PRIMARY KEY,
    NM_ORI_ACO VARCHAR(100) NOT NULL,
    DE_ORI_ACO VARCHAR(700) NOT NULL,
    ST_ORI_ACO INT NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS T696PARA (
    CH_PRM VARCHAR(15) PRIMARY KEY,
    NM_PRM VARCHAR(100) NOT NULL,
    DE_PRM VARCHAR(255) NULL,
    TP_PRM INT NOT NULL,
    VR_PRM VARCHAR(200) NOT NULL,
    MT_USU_ALT VARCHAR(10) NULL,
    NM_USU_ALT VARCHAR(100) NULL,
    DH_ALT TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS T696PLEM (
    SQ_PLJ_EMP INT AUTO_INCREMENT PRIMARY KEY,
    NM_PLJ_EMP VARCHAR(100) NOT NULL,
    DT_INI_VIG TIMESTAMP NOT NULL,
    DT_FIN_VIG TIMESTAMP NOT NULL,
    DE_HST CLOB NOT NULL,
    MT_USU_ALT VARCHAR(10) NULL,
    NM_USU_ALT VARCHAR(100) NULL,
    DH_ALT TIMESTAMP NULL,
    ST_PLJ_EMP INT NOT NULL
);

CREATE TABLE IF NOT EXISTS T696PTMN (
    SQ_PAT_MIN INT AUTO_INCREMENT PRIMARY KEY,
    NM_PAT_MIN VARCHAR(100) NOT NULL,
    SQ_TP_FRU INT NOT NULL,
    DE_HST CLOB NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    DT_INI_VIG TIMESTAMP NOT NULL,
    DT_FIM_VIG TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS T696QUAL (
    SQ_QLF INT AUTO_INCREMENT PRIMARY KEY,
    NM_QLF VARCHAR(100) NOT NULL,
    DE_QLF VARCHAR(500) NULL,
    TP_QLF CHAR(1) NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_QLF INT NOT NULL,
    ID_RNK BOOLEAN NULL
);

CREATE TABLE IF NOT EXISTS T696TEMA (
    SQ_TEM INT AUTO_INCREMENT PRIMARY KEY,
    NM_TEM VARCHAR(1000) NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_TEM INT NOT NULL
);

CREATE TABLE IF NOT EXISTS T696TPFR (
    SQ_TP_FRU INT AUTO_INCREMENT PRIMARY KEY,
    NM_TP_FRU VARCHAR(1000) NOT NULL,
    DE_MNT_CNV CLOB NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_TP_FRU INT NOT NULL,
    ID_EXG_AVL_DSP BOOLEAN NULL,
    DE_MSG_DVU_ATA CLOB NULL
);

CREATE TABLE IF NOT EXISTS T696TPNT (
    CH_TP_NOT VARCHAR(15) PRIMARY KEY,
    NM_TP_NOT VARCHAR(100) NOT NULL,
    DE_TP_NOT VARCHAR(1000) NOT NULL,
    DE_AS_MSG VARCHAR(100) NOT NULL,
    TT_MSG CLOB NOT NULL,
    ID_PR CHAR(1) NOT NULL,
    QT_DD INT NOT NULL,
    DD_INI INT NOT NULL,
    MM_INI INT NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_TP_NOT INT NOT NULL
);

CREATE TABLE IF NOT EXISTS T696TPPL (
    SQ_TP_PLN INT AUTO_INCREMENT PRIMARY KEY,
    NM_TP_PLN VARCHAR(100) NOT NULL,
    NR_NIV SMALLINT NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_TP_PLN INT NOT NULL
);

-- Tabelas com FK

CREATE TABLE IF NOT EXISTS T696ANAC (
    SQ_ANX_ACO INT AUTO_INCREMENT PRIMARY KEY,
    SQ_ACO INT NOT NULL,
    DE_ANX VARCHAR(100) NOT NULL,
    DE_LNK_ANX VARCHAR(100) NOT NULL,
    CONSTRAINT FK_ANAC_ACAO_01 FOREIGN KEY (SQ_ACO) REFERENCES T696ACAO(SQ_ACO)
);

CREATE TABLE IF NOT EXISTS T696ANFR (
    SQ_ANX_FRU INT AUTO_INCREMENT PRIMARY KEY,
    SQ_FRU INT NOT NULL,
    DE_ANX VARCHAR(100) NOT NULL,
    DE_LNK_ANX VARCHAR(100) NOT NULL,
    CONSTRAINT FK_ANFR_FORU_01 FOREIGN KEY (SQ_FRU) REFERENCES T696FORU(SQ_FRU)
);

CREATE TABLE IF NOT EXISTS T696APUS (
    SQ_ATV_PEN_USU INT AUTO_INCREMENT PRIMARY KEY,
    CH_TP_NOT VARCHAR(15) NULL,
    MT_USU VARCHAR(10) NOT NULL,
    DH_NOT TIMESTAMP NOT NULL,
    CONSTRAINT FK_APUS_TPNT_01 FOREIGN KEY (CH_TP_NOT) REFERENCES T696TPNT(CH_TP_NOT)
);

CREATE TABLE IF NOT EXISTS T696DIES (
    SQ_DRT_ETT INT AUTO_INCREMENT PRIMARY KEY,
    SQ_PLJ_EMP INT NOT NULL,
    DE_DRT_ETT VARCHAR(255) NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_DRT_ETT INT NOT NULL,
    CONSTRAINT FK_DIES_PLEM_01 FOREIGN KEY (SQ_PLJ_EMP) REFERENCES T696PLEM(SQ_PLJ_EMP)
);

CREATE TABLE IF NOT EXISTS T696DOMI (
    SQ_DMN INT AUTO_INCREMENT PRIMARY KEY,
    SQ_QLF INT NULL,
    NM_DMN VARCHAR(100) NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    CONSTRAINT FK_DOMI_QUAL_01 FOREIGN KEY (SQ_QLF) REFERENCES T696QUAL(SQ_QLF)
);

CREATE TABLE IF NOT EXISTS T696DOUN (
    SQ_DMN_UND INT AUTO_INCREMENT PRIMARY KEY,
    CD_UND INT NOT NULL,
    SQ_DMN INT NULL,
    CONSTRAINT FK_DOUN_DOMI_01 FOREIGN KEY (SQ_DMN) REFERENCES T696DOMI(SQ_DMN)
);

CREATE TABLE IF NOT EXISTS T696FRCN (
    SQ_FRU_CNV INT AUTO_INCREMENT PRIMARY KEY,
    SQ_FRU INT NOT NULL,
    MT_EPG VARCHAR(10) NOT NULL,
    TP_PTC INT NOT NULL,
    ID_PTC INT NULL,
    CONSTRAINT FK_FRCN_FORU_01 FOREIGN KEY (SQ_FRU) REFERENCES T696FORU(SQ_FRU)
);

CREATE TABLE IF NOT EXISTS T696FRTM (
    SQ_FRU_TEM INT AUTO_INCREMENT PRIMARY KEY,
    SQ_FRU INT NOT NULL,
    SQ_TEM INT NOT NULL,
    NR_ORD_EXB INT NOT NULL,
    ID_ORI_TEM INT NOT NULL,
    DE_TRT_TEM CLOB NULL,
    CONSTRAINT FK_FRTM_FORU_01 FOREIGN KEY (SQ_FRU) REFERENCES T696FORU(SQ_FRU),
    CONSTRAINT FK_FRTM_TEMA_01 FOREIGN KEY (SQ_TEM) REFERENCES T696TEMA(SQ_TEM)
);

CREATE TABLE IF NOT EXISTS T696IMAD (
    SQ_IT_MOD_AVL INT AUTO_INCREMENT PRIMARY KEY,
    SQ_MOD_AVL_DSP INT NOT NULL,
    NR_ORD_EXB INT NOT NULL,
    NM_IT VARCHAR(100) NOT NULL,
    ID_TP_IT CHAR(1) NOT NULL,
    CONSTRAINT FK_IMAD_MOAD_01 FOREIGN KEY (SQ_MOD_AVL_DSP) REFERENCES T696MOAD(SQ_MOD_AVL_DSP)
);

CREATE TABLE IF NOT EXISTS T696MGVR (
    SQ_MBR_GP INT AUTO_INCREMENT PRIMARY KEY,
    SQ_GP_VR_REA INT NOT NULL,
    MT_EPG VARCHAR(7) NOT NULL,
    CONSTRAINT FK_MGVR_GRVR_01 FOREIGN KEY (SQ_GP_VR_REA) REFERENCES T696GRVR(SQ_GP_VR_REA)
);

CREATE TABLE IF NOT EXISTS T696ORES (
    SQ_ORT_ETT INT AUTO_INCREMENT PRIMARY KEY,
    SQ_DRT_ETT INT NOT NULL,
    DE_ORT_ETT CLOB NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_ORT_ETT INT NOT NULL,
    CONSTRAINT FK_ORES_DIES_01 FOREIGN KEY (SQ_DRT_ETT) REFERENCES T696DIES(SQ_DRT_ETT)
);

CREATE TABLE IF NOT EXISTS T696OSIA (
    SQ_OPC_SEL INT AUTO_INCREMENT PRIMARY KEY,
    SQ_IT_MOD_AVL INT NOT NULL,
    DE_OPC_SEL VARCHAR(100) NOT NULL,
    CONSTRAINT FK_OSIA_IMAD_01 FOREIGN KEY (SQ_IT_MOD_AVL) REFERENCES T696IMAD(SQ_IT_MOD_AVL)
);

CREATE TABLE IF NOT EXISTS T696PLAN (
    SQ_PLN INT AUTO_INCREMENT PRIMARY KEY,
    SQ_PLJ_EMP INT NULL,
    SQ_GP_UND INT NULL,
    SQ_TP_PLN INT NULL,
    NM_PLN VARCHAR(100) NOT NULL,
    AA_PLN SMALLINT NOT NULL,
    DE_HST CLOB NOT NULL,
    DT_POS TIMESTAMP NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_PLN INT NULL,
    CONSTRAINT FK_PLAN_GPUN_01 FOREIGN KEY (SQ_GP_UND) REFERENCES T696GPUN(SQ_GP_UND),
    CONSTRAINT FK_PLAN_PLEM_01 FOREIGN KEY (SQ_PLJ_EMP) REFERENCES T696PLEM(SQ_PLJ_EMP),
    CONSTRAINT FK_PLAN_TPPL_01 FOREIGN KEY (SQ_TP_PLN) REFERENCES T696TPPL(SQ_TP_PLN)
);

CREATE TABLE IF NOT EXISTS T696PMGU (
    SQ_PAT_GP_UND INT AUTO_INCREMENT PRIMARY KEY,
    SQ_PAT_MIN INT NOT NULL,
    SQ_GP_UND INT NOT NULL,
    CONSTRAINT FK_PMGU_GPUN_01 FOREIGN KEY (SQ_GP_UND) REFERENCES T696GPUN(SQ_GP_UND)
);

CREATE TABLE IF NOT EXISTS T696PMTM (
    SQ_PAT_MIN_TEM INT AUTO_INCREMENT PRIMARY KEY,
    SQ_PAT_MIN INT NOT NULL,
    SQ_TEM INT NOT NULL,
    NR_ORD_EXB INT NOT NULL,
    CONSTRAINT FK_PMTM_TEMA_01 FOREIGN KEY (SQ_TEM) REFERENCES T696TEMA(SQ_TEM)
);

CREATE TABLE IF NOT EXISTS T696SGRM (
    SQ_SUB_REG_MTA INT AUTO_INCREMENT PRIMARY KEY,
    SQ_GP_REG_MTA INT NOT NULL,
    NM_SUB_REG_MTA VARCHAR(100) NOT NULL,
    CD_UND_ABG INT NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    CONSTRAINT FK_SGRM_GPRM_01 FOREIGN KEY (SQ_GP_REG_MTA) REFERENCES T696GPRM(SQ_GP_REG_MTA)
);

CREATE TABLE IF NOT EXISTS T696UNGP (
    SQ_UND_GP INT AUTO_INCREMENT PRIMARY KEY,
    SQ_GP_UND INT NULL,
    CD_UND INT NOT NULL,
    CONSTRAINT FK_UNGP_GPUN_01 FOREIGN KEY (SQ_GP_UND) REFERENCES T696GPUN(SQ_GP_UND)
);

CREATE TABLE IF NOT EXISTS T696UNPL (
    SQ_PLN_UND INT AUTO_INCREMENT PRIMARY KEY,
    SQ_PLN INT NOT NULL,
    CD_UND INT NOT NULL,
    CONSTRAINT FK_UNPL_PLAN_01 FOREIGN KEY (SQ_PLN) REFERENCES T696PLAN(SQ_PLN)
);

CREATE TABLE IF NOT EXISTS T696VARI (
    SQ_VRV INT AUTO_INCREMENT PRIMARY KEY,
    SQ_NAT INT NOT NULL,
    NM_VRV VARCHAR(100) NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_VRV INT NOT NULL,
    SG_SIS_ORI VARCHAR(20) NULL,
    CONSTRAINT FK_VARI_NATV_01 FOREIGN KEY (SQ_NAT) REFERENCES T696NATV(SQ_NAT)
);

CREATE TABLE IF NOT EXISTS T696VLRD (
    SQ_VR_DIA_REA BIGINT AUTO_INCREMENT PRIMARY KEY,
    SQ_LOT BIGINT NOT NULL,
    CD_UND INT NOT NULL,
    SQ_VRV INT NOT NULL,
    DT_REF TIMESTAMP NOT NULL,
    VR_DIA DECIMAL(15,2) NULL,
    VR_ACM_MM DECIMAL(15,2) NOT NULL,
    VR_ACM_AA DECIMAL(15,2) NOT NULL,
    CONSTRAINT FK_VLRD_LTVR_01 FOREIGN KEY (SQ_LOT) REFERENCES T696LTVR(SQ_LOT),
    CONSTRAINT FK_VLRD_VARI_01 FOREIGN KEY (SQ_VRV) REFERENCES T696VARI(SQ_VRV)
);

CREATE TABLE IF NOT EXISTS T696BLVR (
    SQ_BLQ_VR_REA INT AUTO_INCREMENT PRIMARY KEY,
    SQ_PLN INT NULL,
    SQ_PR INT NULL,
    CONSTRAINT FK_BLVR_PLAN_01 FOREIGN KEY (SQ_PLN) REFERENCES T696PLAN(SQ_PLN)
);

CREATE TABLE IF NOT EXISTS T696INDI (
    SQ_ID INT AUTO_INCREMENT PRIMARY KEY,
    SQ_PLN INT NOT NULL,
    SQ_ID_PAI INT NULL,
    SQ_VRV INT NOT NULL,
    NR_ORD_EXB INT NOT NULL,
    CD_UND_GES_ID INT NOT NULL,
    VR_PSO DECIMAL(5,2) NOT NULL,
    VR_PSO_MIN DECIMAL(5,2) NOT NULL,
    VR_TET_MAX DECIMAL(5,2) NOT NULL,
    ID_TEM_MTA BOOLEAN NOT NULL,
    ID_VSB BOOLEAN NOT NULL,
    TP_REG_VR_REA INT NOT NULL,
    SQ_PLN_CSD_VR INT NULL,
    TP_ABG_CSD_VR INT NOT NULL,
    TP_CLC INT NULL,
    TP_CLC_PFM INT NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ID_AVL_DSP CHAR(1) NULL,
    PR_AVL_DSP CHAR(1) NULL,
    VR_DSP_MNM_RQR DECIMAL(5,2) NULL,
    VR_DSP_MAX_ESP DECIMAL(5,2) NULL,
    TP_ID_BNS INT DEFAULT 1 NOT NULL,
    CONSTRAINT FK_INDI_INDI_01 FOREIGN KEY (SQ_ID_PAI) REFERENCES T696INDI(SQ_ID),
    CONSTRAINT FK_INDI_PLAN_01 FOREIGN KEY (SQ_PLN) REFERENCES T696PLAN(SQ_PLN),
    CONSTRAINT FK_INDI_PLAN_02 FOREIGN KEY (SQ_PLN_CSD_VR) REFERENCES T696PLAN(SQ_PLN),
    CONSTRAINT FK_INDI_VARI_01 FOREIGN KEY (SQ_VRV) REFERENCES T696VARI(SQ_VRV)
);

CREATE TABLE IF NOT EXISTS T696MADP (
    SQ_MOD_AVL_PLN INT AUTO_INCREMENT PRIMARY KEY,
    SQ_MOD_AVL_DSP INT NOT NULL,
    SQ_PLN INT NOT NULL,
    CONSTRAINT FK_MADP_MOAD_01 FOREIGN KEY (SQ_MOD_AVL_DSP) REFERENCES T696MOAD(SQ_MOD_AVL_DSP),
    CONSTRAINT FK_MADP_PLAN_01 FOREIGN KEY (SQ_PLN) REFERENCES T696PLAN(SQ_PLN)
);

CREATE TABLE IF NOT EXISTS T696MSRM (
    SQ_MBR_SUB_REG INT AUTO_INCREMENT PRIMARY KEY,
    SQ_SUB_REG_MTA INT NULL,
    MT_EPG VARCHAR(7) NULL,
    CONSTRAINT FK_MSRM_SGRM_01 FOREIGN KEY (SQ_SUB_REG_MTA) REFERENCES T696SGRM(SQ_SUB_REG_MTA)
);

CREATE TABLE IF NOT EXISTS T696MTSU (
    SQ_MTA_SUG BIGINT AUTO_INCREMENT PRIMARY KEY,
    SQ_ID INT NULL,
    SQ_GP_REG_MTA INT NULL,
    CD_UND INT NOT NULL,
    VR_MTA DECIMAL(15,2) NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    CONSTRAINT FK_MTSU_GPRM_01 FOREIGN KEY (SQ_GP_REG_MTA) REFERENCES T696GPRM(SQ_GP_REG_MTA),
    CONSTRAINT FK_MTSU_INDI_01 FOREIGN KEY (SQ_ID) REFERENCES T696INDI(SQ_ID)
);

CREATE TABLE IF NOT EXISTS T696MVRA (
    SQ_MTA_ANU BIGINT AUTO_INCREMENT PRIMARY KEY,
    SQ_ID INT NOT NULL,
    CD_UND INT NOT NULL,
    VR_MTA_ANU DECIMAL(15,2) NULL,
    VR_REA_ANU DECIMAL(15,2) NULL,
    DT_POS_REA TIMESTAMP NULL,
    MT_USU_ALT_MTA VARCHAR(10) NOT NULL,
    NM_USU_ALT_MTA VARCHAR(100) NOT NULL,
    DH_ALT_MTA TIMESTAMP NOT NULL,
    MT_USU_ALT_REA VARCHAR(10) NULL,
    NM_USU_ALT_REA VARCHAR(100) NULL,
    DH_ALT_REA TIMESTAMP NULL,
    CONSTRAINT FK_MVRA_INDI_01 FOREIGN KEY (SQ_ID) REFERENCES T696INDI(SQ_ID)
);

CREATE TABLE IF NOT EXISTS T696MVRM (
    SQ_MTA_MEN BIGINT AUTO_INCREMENT PRIMARY KEY,
    SQ_MTA_ANU BIGINT NOT NULL,
    DT_REF_MTA TIMESTAMP NOT NULL,
    VR_MTA_MEN DECIMAL(15,2) NULL,
    VR_MTA_ACM DECIMAL(15,2) NULL,
    VR_REA_MEN DECIMAL(15,2) NULL,
    VR_REA_ACM DECIMAL(15,2) NULL,
    DT_POS_REA TIMESTAMP NULL,
    VR_PNT_MEN DECIMAL(15,2) NULL,
    VR_PNT_ACM DECIMAL(15,2) NULL,
    VR_PRM_MEN DECIMAL(15,2) NULL,
    VR_PRM_ACM DECIMAL(15,2) NULL,
    MT_USU_ALT_MTA VARCHAR(10) NOT NULL,
    NM_USU_ALT_MTA VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    MT_USU_ALT_REA VARCHAR(10) NULL,
    NM_USU_ALT_REA VARCHAR(100) NULL,
    DH_ALT_REA TIMESTAMP NULL,
    VR_PSO_AJT DECIMAL(15,2) NULL,
    CONSTRAINT FK_MVRM_MVRA_01 FOREIGN KEY (SQ_MTA_ANU) REFERENCES T696MVRA(SQ_MTA_ANU) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS T696PEUN (
    SQ_PRM_UND BIGINT AUTO_INCREMENT PRIMARY KEY,
    SQ_PLN_UND INT NOT NULL,
    DT_REF TIMESTAMP NOT NULL,
    VR_PNT_MAX DECIMAL(15,2) NOT NULL,
    VR_PNT_REA DECIMAL(15,2) NOT NULL,
    VR_PRM_UND DECIMAL(5,2) NOT NULL,
    ID_CL_UND INT NULL,
    VR_PNT_APD DECIMAL(15,2) DEFAULT 0 NOT NULL,
    NR_RNK INT NULL,
    CONSTRAINT FK_PEUN_UNPL_01 FOREIGN KEY (SQ_PLN_UND) REFERENCES T696UNPL(SQ_PLN_UND)
);

CREATE TABLE IF NOT EXISTS T696POAC (
    SQ_PTF_ACO INT AUTO_INCREMENT PRIMARY KEY,
    NM_PTF VARCHAR(100) NOT NULL,
    AA_REA INT NOT NULL,
    SQ_PLJ_EMP INT NOT NULL,
    SQ_VRV INT NOT NULL,
    ST_PTF_ACO INT NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    DE_HST CLOB NULL,
    CONSTRAINT FK_POAC_PLEM_01 FOREIGN KEY (SQ_PLJ_EMP) REFERENCES T696PLEM(SQ_PLJ_EMP),
    CONSTRAINT FK_POAC_VARI_01 FOREIGN KEY (SQ_VRV) REFERENCES T696VARI(SQ_VRV)
);

CREATE TABLE IF NOT EXISTS T696PSRM (
    SQ_PLN_SUB_GP INT AUTO_INCREMENT PRIMARY KEY,
    SQ_SUB_GP_REG INT NULL,
    SQ_PLN INT NULL,
    DT_INI_INC_MTA TIMESTAMP NOT NULL,
    DT_FIN_INC_MTA TIMESTAMP NOT NULL,
    CONSTRAINT FK_PSRM_PLAN_01 FOREIGN KEY (SQ_PLN) REFERENCES T696PLAN(SQ_PLN),
    CONSTRAINT FK_PSRM_SGRM_01 FOREIGN KEY (SQ_SUB_GP_REG) REFERENCES T696SGRM(SQ_SUB_REG_MTA)
);

CREATE TABLE IF NOT EXISTS T696RCTU (
    SQ_RGR_CAT INT AUTO_INCREMENT PRIMARY KEY,
    SQ_DMN INT NOT NULL,
    SQ_ID_NT_CAT INT NULL,
    NM_RGR_CAT VARCHAR(100) NOT NULL,
    TP_ABG_NT_CAT INT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_RGR_CAT INT NOT NULL,
    MT_USU_ALT VARCHAR(10) DEFAULT 'F134678' NOT NULL,
    CONSTRAINT FK_RCTU_DOMI_01 FOREIGN KEY (SQ_DMN) REFERENCES T696DOMI(SQ_DMN),
    CONSTRAINT FK_RCTU_INDI_01 FOREIGN KEY (SQ_ID_NT_CAT) REFERENCES T696INDI(SQ_ID)
);

CREATE TABLE IF NOT EXISTS T696VIES (
    SQ_VNC_ETT INT AUTO_INCREMENT PRIMARY KEY,
    SQ_ID INT NULL,
    SQ_ORT_ETT INT NULL,
    CONSTRAINT FK_VIES_INDI_01 FOREIGN KEY (SQ_ID) REFERENCES T696INDI(SQ_ID),
    CONSTRAINT FK_VIES_ORES_01 FOREIGN KEY (SQ_ORT_ETT) REFERENCES T696ORES(SQ_ORT_ETT)
);

CREATE TABLE IF NOT EXISTS T696ACES (
    SQ_ACO_ETT INT AUTO_INCREMENT PRIMARY KEY,
    NM_ACO_ETT VARCHAR(100) NOT NULL,
    DE_ACO_ETT VARCHAR(700) NOT NULL,
    SQ_ORI_ACO INT NOT NULL,
    CD_UND INT NULL,
    DH_LIM TIMESTAMP NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_ACO_ETT INT NOT NULL,
    DE_HST CLOB NULL,
    MT_USU_RSP VARCHAR(10) NULL,
    CD_UND_APR INT NULL,
    SQ_PTF_ACO INT NOT NULL,
    TP_ACO_ETT INT DEFAULT 3 NOT NULL,
    VR_PSO DECIMAL(5,2) NULL,
    CONSTRAINT FK_ACES_ORAC_01 FOREIGN KEY (SQ_ORI_ACO) REFERENCES T696ORAC(SQ_ORI_ACO),
    CONSTRAINT FK_ACES_POAC_01 FOREIGN KEY (SQ_PTF_ACO) REFERENCES T696POAC(SQ_PTF_ACO)
);

CREATE TABLE IF NOT EXISTS T696ADES (
    SQ_AVL_DSP INT AUTO_INCREMENT PRIMARY KEY,
    SQ_MOD_AVL_DSP INT NOT NULL,
    CD_UND INT NOT NULL,
    SQ_ID INT NOT NULL,
    PR_AVL TIMESTAMP NOT NULL,
    VR_MTA_ACM_ID DECIMAL(15,2) NOT NULL,
    VR_REA_ACM_ID DECIMAL(15,2) NOT NULL,
    PC_DSP_PR_AVL DECIMAL(15,2) NOT NULL,
    PC_DSP_PR_ANT DECIMAL(15,2) NULL,
    DE_HST CLOB NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    ST_AVL_DSP INT NOT NULL,
    CONSTRAINT FK_ADES_INDI_01 FOREIGN KEY (SQ_ID) REFERENCES T696INDI(SQ_ID),
    CONSTRAINT FK_ADES_MOAD_01 FOREIGN KEY (SQ_MOD_AVL_DSP) REFERENCES T696MOAD(SQ_MOD_AVL_DSP)
);

CREATE TABLE IF NOT EXISTS T696ANAD (
    SQ_ANX_AVL_DSP INT AUTO_INCREMENT PRIMARY KEY,
    SQ_AVL_DSP INT NOT NULL,
    DE_ANX VARCHAR(100) NOT NULL,
    DE_LNK_ARQ_ANX VARCHAR(100) NOT NULL,
    CONSTRAINT FK_ANAD_ADES_01 FOREIGN KEY (SQ_AVL_DSP) REFERENCES T696ADES(SQ_AVL_DSP)
);

CREATE TABLE IF NOT EXISTS T696CLRC (
    SQ_CL INT AUTO_INCREMENT PRIMARY KEY,
    SQ_RGR_CAT INT NOT NULL,
    NR_CL INT NOT NULL,
    FX_INI DECIMAL(5,2) NOT NULL,
    FX_FIN DECIMAL(5,2) NOT NULL,
    VR_PSO DECIMAL(5,2) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    CONSTRAINT FK_CLRC_RCTU_01 FOREIGN KEY (SQ_RGR_CAT) REFERENCES T696RCTU(SQ_RGR_CAT)
);

CREATE TABLE IF NOT EXISTS T696COAC (
    SQ_CTL_ACO INT AUTO_INCREMENT PRIMARY KEY,
    SQ_ACO_ETT INT NOT NULL,
    NM_CPO_ALT VARCHAR(150) NOT NULL,
    VR_ANT CLOB NOT NULL,
    VR_NOV CLOB NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    CONSTRAINT FK_COAC_ACES_01 FOREIGN KEY (SQ_ACO_ETT) REFERENCES T696ACES(SQ_ACO_ETT)
);

CREATE TABLE IF NOT EXISTS T696DMMI (
    SQ_DTR_MEN_MTA INT AUTO_INCREMENT PRIMARY KEY,
    SQ_ID INT NULL,
    MM_CRP_VR_MTA INT NULL,
    VR_DTR_MEN_MTA DECIMAL(5,2) NULL,
    CONSTRAINT FK_DMMI_INDI_01 FOREIGN KEY (SQ_ID) REFERENCES T696INDI(SQ_ID)
);

CREATE TABLE IF NOT EXISTS T696DOAC (
    SQ_ID_DMN INT AUTO_INCREMENT PRIMARY KEY,
    SQ_ACO_ETT INT NOT NULL,
    SQ_DMN INT NOT NULL,
    CONSTRAINT FK_DOAC_ACES_01 FOREIGN KEY (SQ_ACO_ETT) REFERENCES T696ACES(SQ_ACO_ETT),
    CONSTRAINT FK_DOAC_DOMI_01 FOREIGN KEY (SQ_DMN) REFERENCES T696DOMI(SQ_DMN)
);

CREATE TABLE IF NOT EXISTS T696DOIN (
    SQ_ID_DMN INT AUTO_INCREMENT PRIMARY KEY,
    SQ_ID INT NOT NULL,
    SQ_DMN INT NOT NULL,
    CONSTRAINT FK_DOIN_DOMI_01 FOREIGN KEY (SQ_DMN) REFERENCES T696DOMI(SQ_DMN),
    CONSTRAINT FK_DOIN_INDI_01 FOREIGN KEY (SQ_ID) REFERENCES T696INDI(SQ_ID)
);

CREATE TABLE IF NOT EXISTS T696DUPL (
    SQ_DMN_UND_PLN INT AUTO_INCREMENT PRIMARY KEY,
    SQ_DMN INT NOT NULL,
    SQ_PRM_UND BIGINT NULL,
    NR_RNK INT NOT NULL,
    CONSTRAINT FK_DUPL_DOMI_01 FOREIGN KEY (SQ_DMN) REFERENCES T696DOMI(SQ_DMN),
    CONSTRAINT FK_DUPL_PEUN_01 FOREIGN KEY (SQ_PRM_UND) REFERENCES T696PEUN(SQ_PRM_UND)
);

CREATE TABLE IF NOT EXISTS T696ETAC (
    SQ_ETP_ACO INT AUTO_INCREMENT PRIMARY KEY,
    SQ_ACO_ETT INT NOT NULL,
    CD_UND INT NOT NULL,
    DE_ETP_ACO VARCHAR(100) NOT NULL,
    DE_ENT_ETP_ACO CLOB NOT NULL,
    DH_ALT TIMESTAMP NULL,
    MT_USU_ALT VARCHAR(10) NULL,
    NM_USU_ALT VARCHAR(100) NULL,
    ST_ETP_ACO INT NOT NULL,
    AA_REA INT NOT NULL,
    PC_REA_TOT DECIMAL(5,2) DEFAULT 0 NOT NULL,
    ST_REP INT DEFAULT 0 NOT NULL,
    CONSTRAINT FK_ETAC_ACES_01 FOREIGN KEY (SQ_ACO_ETT) REFERENCES T696ACES(SQ_ACO_ETT)
);

CREATE TABLE IF NOT EXISTS T696IGVR (
    SQ_ID_GP INT AUTO_INCREMENT PRIMARY KEY,
    SQ_GP_VR_REA INT NOT NULL,
    SQ_ID INT NOT NULL,
    CONSTRAINT FK_IGVR_GRVR_01 FOREIGN KEY (SQ_GP_VR_REA) REFERENCES T696GRVR(SQ_GP_VR_REA),
    CONSTRAINT FK_IGVR_INDI_01 FOREIGN KEY (SQ_ID) REFERENCES T696INDI(SQ_ID)
);

CREATE TABLE IF NOT EXISTS T696ISRM (
    SQ_ID_SUB_GP INT AUTO_INCREMENT PRIMARY KEY,
    SQ_PLN_SUB_GP INT NULL,
    SQ_ID INT NULL,
    CONSTRAINT FK_ISRM_INDI_01 FOREIGN KEY (SQ_ID) REFERENCES T696INDI(SQ_ID),
    CONSTRAINT FK_ISRM_PSRM_01 FOREIGN KEY (SQ_PLN_SUB_GP) REFERENCES T696PSRM(SQ_PLN_SUB_GP)
);

CREATE TABLE IF NOT EXISTS T696READ (
    SQ_RPT_AVL_DSP INT AUTO_INCREMENT PRIMARY KEY,
    SQ_IT_MOD_AVL INT NOT NULL,
    SQ_AVL_DSP INT NOT NULL,
    DE_RPT_AVL_DSP CLOB NOT NULL,
    CONSTRAINT FK_READ_ADES_01 FOREIGN KEY (SQ_AVL_DSP) REFERENCES T696ADES(SQ_AVL_DSP),
    CONSTRAINT FK_READ_IMAD_01 FOREIGN KEY (SQ_IT_MOD_AVL) REFERENCES T696IMAD(SQ_IT_MOD_AVL)
);

CREATE TABLE IF NOT EXISTS T696RECU (
    SQ_RGR_EPF_CAT INT AUTO_INCREMENT PRIMARY KEY,
    SQ_RGR_CAT INT NOT NULL,
    SQ_ID INT NOT NULL,
    SQ_CL INT NOT NULL,
    TP_OPE INT NOT NULL,
    VR_DSP DECIMAL(5,2) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    DH_ALT TIMESTAMP NOT NULL,
    CONSTRAINT FK_RECU_CLRC_01 FOREIGN KEY (SQ_CL) REFERENCES T696CLRC(SQ_CL),
    CONSTRAINT FK_RECU_INDI_01 FOREIGN KEY (SQ_ID) REFERENCES T696INDI(SQ_ID),
    CONSTRAINT FK_RECU_RCTU_01 FOREIGN KEY (SQ_RGR_CAT) REFERENCES T696RCTU(SQ_RGR_CAT)
);

CREATE TABLE IF NOT EXISTS T696VIAC (
    SQ_VNC_ACO INT AUTO_INCREMENT PRIMARY KEY,
    SQ_ACO_ETT INT NULL,
    SQ_ORT_ETT INT NULL,
    CONSTRAINT FK_VIAC_ACES_01 FOREIGN KEY (SQ_ACO_ETT) REFERENCES T696ACES(SQ_ACO_ETT),
    CONSTRAINT FK_VIAC_ORES_01 FOREIGN KEY (SQ_ORT_ETT) REFERENCES T696ORES(SQ_ORT_ETT)
);

CREATE TABLE IF NOT EXISTS T696ACAD (
    SQ_ACO_AVL_DSP INT AUTO_INCREMENT PRIMARY KEY,
    SQ_AVL_DSP INT NULL,
    SQ_ACO INT NULL,
    CONSTRAINT FK_ACAD_ACAO_01 FOREIGN KEY (SQ_ACO) REFERENCES T696ACAO(SQ_ACO),
    CONSTRAINT FK_ACAD_ADES_01 FOREIGN KEY (SQ_AVL_DSP) REFERENCES T696ADES(SQ_AVL_DSP)
);

CREATE TABLE IF NOT EXISTS T696ENAC (
    SQ_ENT_ACO INT AUTO_INCREMENT PRIMARY KEY,
    SQ_ETP_ACO INT NOT NULL,
    MM_ENT INT NOT NULL,
    PC_PLJ_ENT DECIMAL(5,2) NULL,
    PC_REA_ENT DECIMAL(5,2) NULL,
    DE_REA_ENT CLOB NULL,
    DH_ALT TIMESTAMP NOT NULL,
    MT_USU_ALT VARCHAR(10) NOT NULL,
    NM_USU_ALT VARCHAR(100) NOT NULL,
    ST_ENT_ACO INT NOT NULL,
    DE_HST CLOB NULL,
    NT_REV CLOB NULL,
    CONSTRAINT FK_ENAC_ETAC_01 FOREIGN KEY (SQ_ETP_ACO) REFERENCES T696ETAC(SQ_ETP_ACO)
);

CREATE TABLE IF NOT EXISTS T696APID (
    SQ_APU_ID INT AUTO_INCREMENT PRIMARY KEY,
    SQ_PTF_ACO INT NULL,
    SQ_ACO_ETT INT NULL,
    SQ_ETP_ACO INT NULL,
    SQ_ENT_ACO INT NULL,
    CD_UND INT NULL,
    NM_ULT_MM_PLJ INT NULL,
    NM_ULT_MM_REA INT NULL,
    MM_ATR INT NULL,
    VR_PSO DECIMAL(5,2) NULL,
    CONSTRAINT FK_APID_ACES_01 FOREIGN KEY (SQ_ACO_ETT) REFERENCES T696ACES(SQ_ACO_ETT),
    CONSTRAINT FK_APID_ENAC_01 FOREIGN KEY (SQ_ENT_ACO) REFERENCES T696ENAC(SQ_ENT_ACO),
    CONSTRAINT FK_APID_ETAC_01 FOREIGN KEY (SQ_ETP_ACO) REFERENCES T696ETAC(SQ_ETP_ACO),
    CONSTRAINT FK_APID_POAC_01 FOREIGN KEY (SQ_PTF_ACO) REFERENCES T696POAC(SQ_PTF_ACO)
);
