package com.thadeu.massa_dados_core.mcp;

import com.thadeu.massa_dados_core.mcp.dto.DdlRequest;
import com.thadeu.massa_dados_core.mcp.dto.DdlResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

/**
 * Testes unitários para {@link McpDdlToEntityService}.
 *
 * <p>Responsabilidades:
 * <ul>
 *   <li>Validar conversão de DDL para Entity JPA</li>
 *   <li>Validar tratamento de DDL inválido, vazio ou nulo</li>
 *   <li>Validar extração correta de colunas e tipos</li>
 *   <li>Validar retorno de falha de compilação</li>
 * </ul>
 *
 * @author Thadeu Garrido
 * @version 1.0
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("McpDdlToEntityService")
class McpDdlToEntityServiceTest {

    @Mock
    private McpCompileService compileService;

    private McpDdlToEntityService service;

    /**
     * Configura o serviço antes de cada teste, injetando o caminho temporário.
     */
    @BeforeEach
    void setUp() {
        service = new McpDdlToEntityService(compileService);
        try {
            var field = McpDdlToEntityService.class.getDeclaredField("entityClassesPath");
            field.setAccessible(true);
            field.set(service, System.getProperty("java.io.tmpdir"));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @Test
    @DisplayName("deveLancarExcecaoParaDdlInvalido - DDL sem CREATE TABLE deve lançar IllegalArgumentException")
    void deveLancarExcecaoParaDdlInvalido() {
        DdlRequest request = new DdlRequest("SELECT * FROM tabela");
        assertThrows(IllegalArgumentException.class, () -> service.processDdl(request));
    }

    @Test
    @DisplayName("deveLancarExcecaoParaDdlVazio - DDL vazio deve lançar IllegalArgumentException")
    void deveLancarExcecaoParaDdlVazio() {
        DdlRequest request = new DdlRequest("");
        assertThrows(IllegalArgumentException.class, () -> service.processDdl(request));
    }

    @Test
    @DisplayName("deveLancarExcecaoParaDdlNulo - DDL nulo deve lançar IllegalArgumentException")
    void deveLancarExcecaoParaDdlNulo() {
        DdlRequest request = new DdlRequest(null);
        assertThrows(IllegalArgumentException.class, () -> service.processDdl(request));
    }

    @Test
    @DisplayName("deveProcessarDdlValido - DDL válido deve gerar Entity com sucesso")
    void deveProcessarDdlValido() throws IOException {
        String ddl = "CREATE TABLE T696TESTE (\n" +
                "    SQ_TESTE int GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                "    NM_TESTE varchar(100) NOT NULL,\n" +
                "    DE_TESTE varchar(500) NULL,\n" +
                "    CONSTRAINT PK_TESTE PRIMARY KEY (SQ_TESTE)\n" +
                ");";

        when(compileService.compile()).thenReturn(new McpCompileService.CompileResult(true, "Compilação bem-sucedida"));

        DdlResponse response = service.processDdl(new DdlRequest(ddl));

        assertNotNull(response);
        assertEquals("Teste", response.entityClassName());
        assertEquals("T696TESTE", response.tableName());
        assertTrue(response.compileSuccess());
        assertNotNull(response.entityCode());
        assertTrue(response.entityCode().contains("@Entity"));
        assertTrue(response.entityCode().contains("@Table(name=\"T696TESTE\")"));
        assertTrue(response.entityCode().contains("class Teste implements Serializable"));
    }

    @Test
    @DisplayName("deveRetornarFalhaCompilacao - DDL válido com falha de compilação deve retornar erro")
    void deveRetornarFalhaCompilacao() throws IOException {
        String ddl = "CREATE TABLE T696FALHA (\n" +
                "    SQ_FALHA int GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                "    NM_FALHA varchar(100) NOT NULL,\n" +
                "    CONSTRAINT PK_FALHA PRIMARY KEY (SQ_FALHA)\n" +
                ");";

        when(compileService.compile()).thenReturn(new McpCompileService.CompileResult(false, "Erro de compilação: classe duplicada"));

        DdlResponse response = service.processDdl(new DdlRequest(ddl));

        assertNotNull(response);
        assertFalse(response.compileSuccess());
        assertTrue(response.compileMessage().contains("Erro de compilação"));
    }

    @Test
    @DisplayName("deveExtrairColunasCorretamente - DDL com múltiplos tipos deve mapear corretamente")
    void deveExtrairColunasCorretamente() throws IOException {
        String ddl = "CREATE TABLE T696COLUNAS (\n" +
                "    SQ_COL int GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                "    NM_COL varchar(200) NOT NULL,\n" +
                "    VR_COL decimal(10,2) NULL,\n" +
                "    DT_COL timestamp NOT NULL,\n" +
                "    CONSTRAINT PK_COLUNAS PRIMARY KEY (SQ_COL)\n" +
                ");";

        when(compileService.compile()).thenReturn(new McpCompileService.CompileResult(true, "OK"));

        DdlResponse response = service.processDdl(new DdlRequest(ddl));

        assertNotNull(response);
        assertEquals(4, response.attributes().size());

        assertEquals("Long", response.attributes().get(0).type());
        assertEquals("String", response.attributes().get(1).type());
        assertEquals("BigDecimal", response.attributes().get(2).type());
        assertEquals("LocalDateTime", response.attributes().get(3).type());
    }
}
