package com.thadeu.massa_dados_core.mcp;

import com.thadeu.massa_dados_core.mcp.dto.DdlRequest;
import com.thadeu.massa_dados_core.mcp.dto.DdlResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class McpDdlToEntityServiceTest {

    @Mock
    private McpCompileService compileService;

    private McpDdlToEntityService service;

    @BeforeEach
    void setUp() {
        service = new McpDdlToEntityService(compileService);
        // Usar reflection para setar entityClassesPath
        try {
            var field = McpDdlToEntityService.class.getDeclaredField("entityClassesPath");
            field.setAccessible(true);
            field.set(service, System.getProperty("java.io.tmpdir"));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @Test
    void deveLancarExcecaoParaDdlInvalido() {
        // DDL sem CREATE TABLE
        DdlRequest request = new DdlRequest("SELECT * FROM tabela");
        assertThrows(IllegalArgumentException.class, () -> service.processDdl(request));
    }

    @Test
    void deveLancarExcecaoParaDdlVazio() {
        DdlRequest request = new DdlRequest("");
        assertThrows(IllegalArgumentException.class, () -> service.processDdl(request));
    }

    @Test
    void deveLancarExcecaoParaDdlNulo() {
        DdlRequest request = new DdlRequest(null);
        assertThrows(IllegalArgumentException.class, () -> service.processDdl(request));
    }

    @Test
    void deveProcessarDdlValido() throws IOException {
        String ddl = "CREATE TABLE T696TESTE (\n" +
                "    SQ_TESTE int GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                "    NM_TESTE varchar(100) NOT NULL,\n" +
                "    DE_TESTE varchar(500) NULL,\n" +
                "    CONSTRAINT PK_TESTE PRIMARY KEY (SQ_TESTE)\n" +
                ");";

        when(compileService.compile()).thenReturn(new McpCompileService.CompileResult(true, "Compilação bem-sucedida"));

        DdlResponse response = service.processDdl(new DdlRequest(ddl));

        assertNotNull(response);
        assertEquals("Teste", response.entityClassName());
        assertEquals("T696TESTE", response.tableName());
        assertTrue(response.compileSuccess());
        assertNotNull(response.entityCode());
        assertTrue(response.entityCode().contains("@Entity"));
        assertTrue(response.entityCode().contains("@Table(name=\"T696TESTE\")"));
        assertTrue(response.entityCode().contains("class Teste implements Serializable"));
    }

    @Test
    void deveRetornarFalhaCompilacao() throws IOException {
        String ddl = "CREATE TABLE T696FALHA (\n" +
                "    SQ_FALHA int GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                "    NM_FALHA varchar(100) NOT NULL,\n" +
                "    CONSTRAINT PK_FALHA PRIMARY KEY (SQ_FALHA)\n" +
                ");";

        when(compileService.compile()).thenReturn(new McpCompileService.CompileResult(false, "Erro de compilação: classe duplicada"));

        DdlResponse response = service.processDdl(new DdlRequest(ddl));

        assertNotNull(response);
        assertFalse(response.compileSuccess());
        assertTrue(response.compileMessage().contains("Erro de compilação"));
    }

    @Test
    void deveExtrairColunasCorretamente() throws IOException {
        String ddl = "CREATE TABLE T696COLUNAS (\n" +
                "    SQ_COL int GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                "    NM_COL varchar(200) NOT NULL,\n" +
                "    VR_COL decimal(10,2) NULL,\n" +
                "    DT_COL timestamp NOT NULL,\n" +
                "    CONSTRAINT PK_COLUNAS PRIMARY KEY (SQ_COL)\n" +
                ");";

        when(compileService.compile()).thenReturn(new McpCompileService.CompileResult(true, "OK"));

        DdlResponse response = service.processDdl(new DdlRequest(ddl));

        assertNotNull(response);
        assertEquals(4, response.attributes().size());

        // Verificar tipos mapeados
        assertEquals("Long", response.attributes().get(0).type()); // INT -> Long
        assertEquals("String", response.attributes().get(1).type()); // VARCHAR -> String
        assertEquals("BigDecimal", response.attributes().get(2).type()); // DECIMAL -> BigDecimal
        assertEquals("LocalDateTime", response.attributes().get(3).type()); // TIMESTAMP -> LocalDateTime
    }
}
