package com.thadeu.massa_dados_core.mcp;

import com.thadeu.massa_dados_core.mcp.dto.UnknownEntityRequest;
import com.thadeu.massa_dados_core.mcp.dto.UnknownEntityResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Testes unitários para {@link McpUnknownEntityService}.
 *
 * <p>Responsabilidades:
 * <ul>
 *   <li>Validar identificação de tabelas faltantes</li>
 *   <li>Validar retorno de lista vazia para DDL vazio</li>
 *   <li>Validar retorno de lista vazia para DDL sem CREATE TABLE</li>
 * </ul>
 *
 * @author Thadeu Garrido
 * @version 1.0
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("McpUnknownEntityService")
class McpUnknownEntityServiceTest {

    private McpUnknownEntityService service;

    /**
     * Configura o serviço antes de cada teste com diretório temporário.
     */
    @BeforeEach
    void setUp() {
        service = new McpUnknownEntityService();
        ReflectionTestUtils.setField(service, "entityClassesPath", System.getProperty("java.io.tmpdir"));
    }

    @Test
    @DisplayName("deveIdentificarTabelasFaltantes - DDL com tabela nova deve retornar como faltante")
    void deveIdentificarTabelasFaltantes() throws IOException {
        String ddl = "CREATE TABLE T696NOVA (\n" +
                "    SQ_NOVA int GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                "    NM_NOVA varchar(100) NOT NULL,\n" +
                "    CONSTRAINT PK_NOVA PRIMARY KEY (SQ_NOVA)\n" +
                ");";

        UnknownEntityResponse response = service.identify(new UnknownEntityRequest(ddl));

        assertNotNull(response);
        assertTrue(response.missingTables().contains("T696NOVA"));
    }

    @Test
    @DisplayName("deveRetornarListaVaziaParaDdlVazio - DDL vazio deve retornar listas vazias")
    void deveRetornarListaVaziaParaDdlVazio() throws IOException {
        UnknownEntityResponse response = service.identify(new UnknownEntityRequest(""));

        assertNotNull(response);
        assertTrue(response.missingTables().isEmpty());
        assertTrue(response.missingColumns().isEmpty());
    }

    @Test
    @DisplayName("deveRetornarListaVaziaParaDdlSemCreateTable - DDL sem CREATE TABLE deve retornar listas vazias")
    void deveRetornarListaVaziaParaDdlSemCreateTable() throws IOException {
        UnknownEntityResponse response = service.identify(new UnknownEntityRequest("SELECT * FROM tabela"));

        assertNotNull(response);
        assertTrue(response.missingTables().isEmpty());
        assertTrue(response.missingColumns().isEmpty());
    }
}
