package com.thadeu.massa_dados_core.mcp;

import com.thadeu.massa_dados_core.mcp.dto.UnknownEntityRequest;
import com.thadeu.massa_dados_core.mcp.dto.UnknownEntityResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
class McpUnknownEntityServiceTest {

    private McpUnknownEntityService service;

    @BeforeEach
    void setUp() {
        service = new McpUnknownEntityService();
        // Usar um diretório temporário para evitar dependência de arquivos reais
        ReflectionTestUtils.setField(service, "entityClassesPath", System.getProperty("java.io.tmpdir"));
    }

    @Test
    void deveIdentificarTabelasFaltantes() throws IOException {
        String ddl = "CREATE TABLE T696NOVA (\n" +
                "    SQ_NOVA int GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                "    NM_NOVA varchar(100) NOT NULL,\n" +
                "    CONSTRAINT PK_NOVA PRIMARY KEY (SQ_NOVA)\n" +
                ");";

        UnknownEntityResponse response = service.identify(new UnknownEntityRequest(ddl));

        assertNotNull(response);
        // Como não existem classes Entity no diretório temporário, a tabela deve aparecer como faltante
        assertTrue(response.missingTables().contains("T696NOVA"));
    }

    @Test
    void deveRetornarListaVaziaParaDdlVazio() throws IOException {
        UnknownEntityResponse response = service.identify(new UnknownEntityRequest(""));

        assertNotNull(response);
        assertTrue(response.missingTables().isEmpty());
        assertTrue(response.missingColumns().isEmpty());
    }

    @Test
    void deveRetornarListaVaziaParaDdlSemCreateTable() throws IOException {
        UnknownEntityResponse response = service.identify(new UnknownEntityRequest("SELECT * FROM tabela"));

        assertNotNull(response);
        assertTrue(response.missingTables().isEmpty());
        assertTrue(response.missingColumns().isEmpty());
    }
}
